/**
 * Browser-chrome drift check: compares an app's built output (index.html, its web
 * manifest and the icon files) against the standard in docs/BROWSER-CHROME.md and the
 * icons generated by this package. Every problem is reported, not just the first.
 */
import {existsSync, readFileSync} from 'node:fs';
import {join} from 'node:path';

import {
  BRAND_FILES,
  brandAssetsDir,
  manifestFragment,
  SHORT_NAME_MAX,
  themeColors,
  TITLE_SEPARATOR,
  VIEWPORT,
} from './standard.mjs';
import {brandColors} from './tokens.mjs';

/** Head links the standard requires: `rel` + the file it points at (+ fixed attributes). */
const REQUIRED_LINKS = [
  {rel: 'icon', file: 'favicon.ico', attrs: {sizes: '32x32'}},
  {rel: 'icon', file: 'favicon.svg', attrs: {type: 'image/svg+xml'}},
  {rel: 'apple-touch-icon', file: 'apple-touch-icon.png', attrs: {}},
  {rel: 'manifest', file: 'manifest.webmanifest', attrs: {}},
];

const ENTITIES = {amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", '#39': "'"};

function decodeEntities(text) {
  return text.replace(/&(amp|lt|gt|quot|apos|#39);/g, (_, name) => ENTITIES[name]);
}

function parseAttributes(source) {
  const attrs = {};
  for (const [, name, dq, sq, bare] of source.matchAll(
    /([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g
  )) {
    attrs[name.toLowerCase()] = decodeEntities(dq ?? sq ?? bare ?? '');
  }
  return attrs;
}

function tags(head, name) {
  return [...head.matchAll(new RegExp(`<${name}\\b([^>]*)>`, 'gi'))].map(([, a]) =>
    parseAttributes(a)
  );
}

/** Site-root-relative path of an href (`/a.png`, `./a.png`, `a.png` → `a.png`). */
function rootPath(href) {
  if (href === undefined || /^[a-z][a-z\d+.-]*:/i.test(href) || href.startsWith('//')) {
    return null;
  }
  return href.replace(/^\.?\//, '').replace(/[?#].*$/, '');
}

function sameColor(a, b) {
  return typeof a === 'string' && a.trim().toLowerCase() === b.toLowerCase();
}

function normalizeViewport(content) {
  return (content ?? '')
    .split(',')
    .map(part => part.replace(/\s+/g, ''))
    .filter(Boolean)
    .sort()
    .join(',');
}

function relList(attrs) {
  return (attrs.rel ?? '').toLowerCase().split(/\s+/).filter(Boolean);
}

/**
 * Checks an `index.html` against the head template.
 * @param {string} html
 * @param {{appName?: string, colors?: object}} [options]
 * @returns {{rule: string, message: string}[]}
 */
export function checkHead(html, {appName, colors = brandColors()} = {}) {
  const problems = [];
  const report = (rule, message) => problems.push({rule, message});
  const head = /<head\b[^>]*>([\s\S]*?)<\/head>/i.exec(html)?.[1];
  if (head === undefined) {
    report('head', 'index.html has no <head> element');
    return problems;
  }

  const titles = [...head.matchAll(/<title\b[^>]*>([\s\S]*?)<\/title>/gi)].map(([, t]) =>
    decodeEntities(t).trim()
  );
  if (titles.length !== 1 || !titles[0]) {
    report('title', `expected exactly one non-empty <title>, found ${titles.length}`);
  } else if (appName && titles[0] !== appName) {
    report(
      'title',
      `static <title> is "${titles[0]}"; it must be the bare app name "${appName}" ` +
        `(routes set "{Page}${TITLE_SEPARATOR}${appName}" at runtime)`
    );
  }

  const metas = tags(head, 'meta');
  const metaNamed = name => metas.filter(m => (m.name ?? '').toLowerCase() === name);

  const viewport = metaNamed('viewport');
  if (
    viewport.length !== 1 ||
    normalizeViewport(viewport[0].content) !== normalizeViewport(VIEWPORT)
  ) {
    report('viewport', `expected one <meta name="viewport" content="${VIEWPORT}">`);
  }

  const colorScheme = metaNamed('color-scheme');
  if (colorScheme.length !== 1 || (colorScheme[0].content ?? '').trim() !== 'light dark') {
    report('color-scheme', 'expected one <meta name="color-scheme" content="light dark">');
  }

  const expected = themeColors(colors);
  const themeMetas = metaNamed('theme-color');
  for (const scheme of ['light', 'dark']) {
    const media = new RegExp(`^\\(\\s*prefers-color-scheme\\s*:\\s*${scheme}\\s*\\)$`, 'i');
    const matches = themeMetas.filter(m => media.test((m.media ?? '').trim()));
    if (matches.length !== 1 || !sameColor(matches[0].content, expected[scheme])) {
      report(
        'theme-color',
        `expected one <meta name="theme-color" content="${expected[scheme]}" ` +
          `media="(prefers-color-scheme: ${scheme})">`
      );
    }
  }
  if (themeMetas.length !== 2) {
    report('theme-color', `expected exactly two theme-color metas, found ${themeMetas.length}`);
  }

  const links = tags(head, 'link');
  for (const {rel, file, attrs} of REQUIRED_LINKS) {
    const found = links.filter(l => relList(l).includes(rel) && rootPath(l.href) === file);
    const ok =
      found.length === 1 &&
      Object.entries(attrs).every(([k, v]) => (found[0][k] ?? '').toLowerCase() === v);
    if (!ok) {
      const extra = Object.entries(attrs)
        .map(([k, v]) => ` ${k}="${v}"`)
        .join('');
      report('links', `expected one <link rel="${rel}" href="/${file}"${extra}>`);
    }
  }
  const allowedIcons = new Set(REQUIRED_LINKS.map(l => `${l.rel}|${l.file}`));
  for (const link of links) {
    for (const rel of relList(link)) {
      if (!['icon', 'apple-touch-icon', 'mask-icon', 'manifest'].includes(rel)) continue;
      if (!allowedIcons.has(`${rel}|${rootPath(link.href)}`)) {
        report('links', `unexpected <link rel="${rel}" href="${link.href ?? ''}">`);
      }
    }
  }
  return problems;
}

/**
 * Checks a parsed web manifest against the standard.
 * @param {object} manifest
 * @param {{appName?: string, colors?: object}} [options]
 * @returns {{rule: string, message: string}[]}
 */
export function checkManifest(manifest, {appName, colors = brandColors()} = {}) {
  const problems = [];
  const report = message => problems.push({rule: 'manifest', message});
  if (manifest === null || typeof manifest !== 'object' || Array.isArray(manifest)) {
    report('manifest is not a JSON object');
    return problems;
  }

  if (typeof manifest.name !== 'string' || !manifest.name) {
    report('`name` is missing');
  } else if (appName && manifest.name !== appName) {
    report(`\`name\` is "${manifest.name}", expected "${appName}"`);
  }
  if (typeof manifest.short_name !== 'string' || !manifest.short_name) {
    report('`short_name` is missing');
  } else if (manifest.short_name.length > SHORT_NAME_MAX) {
    report(`\`short_name\` "${manifest.short_name}" exceeds ${SHORT_NAME_MAX} characters`);
  }

  const {icons: expectedIcons, ...fields} = manifestFragment(colors);
  for (const [key, value] of Object.entries(fields)) {
    const ok = key.endsWith('_color') ? sameColor(manifest[key], value) : manifest[key] === value;
    if (!ok) {
      report(`\`${key}\` is ${JSON.stringify(manifest[key])}, expected ${JSON.stringify(value)}`);
    }
  }

  const iconKey = i => `${rootPath(i?.src)}|${i?.sizes}|${i?.type}|${(i?.purpose ?? 'any').trim()}`;
  const actual = Array.isArray(manifest.icons) ? manifest.icons.map(iconKey) : [];
  const wanted = expectedIcons.map(iconKey);
  const missing = wanted.filter(k => !actual.includes(k));
  const extra = actual.filter(k => !wanted.includes(k));
  if (missing.length || extra.length || actual.length !== wanted.length) {
    report(
      `\`icons\` must be exactly ${JSON.stringify(expectedIcons)}` +
        (missing.length ? `; missing ${missing.join(', ')}` : '') +
        (extra.length ? `; unexpected ${extra.join(', ')}` : '')
    );
  }
  return problems;
}

/**
 * Checks that the served icon files are byte-identical to the ones this package
 * generated for `app` — a stale, hand-edited or missing icon is drift.
 * @param {string} distDir directory served at the site root
 * @param {string} app the app's mark (`lk`, `fs`, …)
 * @param {{assetsDir?: string}} [options]
 * @returns {{rule: string, message: string}[]}
 */
export function checkIcons(distDir, app, {assetsDir = brandAssetsDir(app)} = {}) {
  const problems = [];
  for (const file of BRAND_FILES) {
    const served = join(distDir, file);
    if (!existsSync(served)) {
      problems.push({rule: 'icons', message: `${file} is missing from ${distDir}`});
    } else if (!readFileSync(served).equals(readFileSync(join(assetsDir, file)))) {
      problems.push({
        rule: 'icons',
        message: `${file} differs from @lifekit-hq/tokens/brand/${app}/${file}`,
      });
    }
  }
  return problems;
}

/**
 * Full drift check of an app's build output directory (served at the site root): the
 * index.html head, the manifest it links, and every icon file.
 * @param {{distDir: string, app: string, appName?: string, index?: string,
 *   assetsDir?: string, colors?: object}} options
 * @returns {{rule: string, message: string}[]} empty when the app follows the standard
 */
export function checkBrowserChrome({
  distDir,
  app,
  appName,
  index = 'index.html',
  assetsDir,
  colors = brandColors(),
}) {
  const indexPath = join(distDir, index);
  if (!existsSync(indexPath)) {
    return [{rule: 'head', message: `${indexPath} does not exist`}];
  }
  const problems = checkHead(readFileSync(indexPath, 'utf8'), {appName, colors});

  const manifestPath = join(distDir, 'manifest.webmanifest');
  if (!existsSync(manifestPath)) {
    problems.push({rule: 'manifest', message: `${manifestPath} does not exist`});
  } else {
    let manifest;
    try {
      manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    } catch (error) {
      problems.push({rule: 'manifest', message: `manifest.webmanifest: ${error.message}`});
    }
    if (manifest !== undefined) problems.push(...checkManifest(manifest, {appName, colors}));
  }

  problems.push(...checkIcons(distDir, app, assetsDir ? {assetsDir} : {}));
  return problems;
}
