/**
 * The browser-chrome standard as data (docs/BROWSER-CHROME.md is the prose). The asset
 * build, the head template, the manifest helper and the drift check all read these
 * constants, so they cannot disagree with each other.
 */
import {fileURLToPath} from 'node:url';

import {BRAND_APPS} from './mark.mjs';
import {brandColors} from './tokens.mjs';

/** Icon files every app serves from its site root, all generated by the tokens build. */
export const BRAND_FILES = Object.freeze([
  'favicon.svg',
  'favicon.ico',
  'apple-touch-icon.png',
  'icon-192.png',
  'icon-512.png',
  'icon-maskable-512.png',
]);

/** Manifest `icons`, in the order apps list them. */
export const MANIFEST_ICONS = Object.freeze([
  Object.freeze({src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any'}),
  Object.freeze({src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any'}),
  Object.freeze({
    src: '/icon-maskable-512.png',
    sizes: '512x512',
    type: 'image/png',
    purpose: 'maskable',
  }),
]);

/** Separator of the `{Page} · {App}` title rule. */
export const TITLE_SEPARATOR = ' · ';

/** Longest `short_name` that fits under a home-screen icon without truncation. */
export const SHORT_NAME_MAX = 12;

/** The viewport meta every app ships. */
export const VIEWPORT = 'width=device-width, initial-scale=1, viewport-fit=cover';

export {BRAND_APPS};

/** Absolute path of an app's generated icon directory inside the installed package. */
export function brandAssetsDir(app) {
  if (!BRAND_APPS.includes(app)) {
    throw new Error(`Unknown lifekit app mark "${app}" (known: ${BRAND_APPS.join(', ')})`);
  }
  return fileURLToPath(new URL(`./dist/${app}/`, import.meta.url));
}

/** `theme-color` per colour scheme: `--color-surface-bg` light / dark. */
export function themeColors(colors = brandColors()) {
  return {light: colors.surfaceLight, dark: colors.surfaceDark};
}

/** Where an app is served when it does not live under a sub-path. */
export const DEFAULT_BASE_PATH = '/';

/**
 * Normalises the path an app is served under to `/segment/…/`: a missing leading or
 * trailing slash is added and repeated slashes collapse. Anything that is not a plain
 * path (empty, a URL, a query or fragment, whitespace, backslashes, `.`/`..` segments)
 * throws, so a typo cannot silently become the manifest scope.
 */
export function normalizeBasePath(basePath = DEFAULT_BASE_PATH) {
  if (typeof basePath !== 'string' || !basePath.trim()) {
    throw new Error('base path must be a non-empty string such as "/console/"');
  }
  if (!/^[\w\-.~%/]+$/.test(basePath) || basePath.split('/').some(s => s === '.' || s === '..')) {
    throw new Error(`invalid base path "${basePath}": expected a plain path such as "/console/"`);
  }
  const segments = basePath.split('/').filter(Boolean);
  return segments.length ? `/${segments.join('/')}/` : DEFAULT_BASE_PATH;
}

/**
 * The standard's manifest fields: colours, icons, display and scope. Apps add `name`
 * and `short_name` (see {@link brandManifest}). `basePath` is where the app is served
 * (default `/`) and sets `id`, `start_url` and `scope`.
 */
export function manifestFragment(colors = brandColors(), {basePath} = {}) {
  const base = normalizeBasePath(basePath);
  return {
    id: base,
    start_url: base,
    scope: base,
    display: 'standalone',
    theme_color: colors.surfaceLight,
    background_color: colors.surfaceLight,
    icons: MANIFEST_ICONS.map(icon => ({...icon})),
  };
}

/**
 * A complete `manifest.webmanifest` for an app. Extra fields (description, lang,
 * shortcuts, …) pass through; the standard's own fields always win.
 */
export function brandManifest({name, shortName, basePath, ...extra}) {
  if (!name) throw new Error('brandManifest: `name` is required');
  const short = shortName ?? name;
  if (short.length > SHORT_NAME_MAX) {
    throw new Error(`brandManifest: short_name "${short}" exceeds ${SHORT_NAME_MAX} characters`);
  }
  return {name, short_name: short, ...extra, ...manifestFragment(undefined, {basePath})};
}

function escapeHtml(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** The head lines every app's `index.html` carries, after `<meta charset>`. */
export function headMarkup({title}, colors = brandColors()) {
  const {light, dark} = themeColors(colors);
  return [
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="viewport" content="${VIEWPORT}" />`,
    '<meta name="color-scheme" content="light dark" />',
    `<meta name="theme-color" content="${light}" media="(prefers-color-scheme: light)" />`,
    `<meta name="theme-color" content="${dark}" media="(prefers-color-scheme: dark)" />`,
    '<link rel="icon" href="/favicon.ico" sizes="32x32" />',
    '<link rel="icon" href="/favicon.svg" type="image/svg+xml" />',
    '<link rel="apple-touch-icon" href="/apple-touch-icon.png" />',
    '<link rel="manifest" href="/manifest.webmanifest" />',
  ].join('\n');
}
