/**
 * Generates seeds/<app>.css, one per app seed in engine/presets.mjs: the derived palette for the
 * light and dark themes plus a `prefers-contrast: more` block. An app imports its file after
 * theme.css. The files are committed so the palette change is reviewable in a diff;
 * test/seed-engine.spec.mjs fails when one is stale.
 *
 *   node projects/tokens/scripts/build-seeds.mjs     (npm run build:seeds at the workspace root)
 */
import {mkdirSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';

import {derive, toCss} from '../engine/derive.mjs';
import {APP_SEEDS} from '../engine/presets.mjs';

export const SEEDS_DIR = fileURLToPath(new URL('../seeds/', import.meta.url));

const LIGHT = ":root,\n[data-theme='light']";
const DARK = "[data-theme='dark']";

/** The stylesheet for one app seed. */
export function seedCss(app) {
  const entry = APP_SEEDS[app];
  if (!entry) throw new Error(`no app seed named ${app}`);
  const {seed, intensity, name} = entry;
  const palette = (mode, contrast) => derive({seed, intensity, mode, contrast}).tokens;
  return [
    `/*\n * @lifekit-hq/tokens seed theme for ${name}: seed ${seed}, intensity ${intensity}.\n` +
      ' * Generated by scripts/build-seeds.mjs from engine/; do not edit. Import after theme.css.\n */\n',
    toCss(LIGHT, palette('light', 'standard')),
    toCss(DARK, palette('dark', 'standard')),
    '@media (prefers-contrast: more) {\n' +
      toCss(LIGHT.replace('\n', '\n  '), palette('light', 'more'), '  ') +
      toCss(DARK, palette('dark', 'more'), '  ') +
      '}\n',
  ].join('\n');
}

/** Writes every app's stylesheet into `outDir`. */
export function buildSeeds({outDir = SEEDS_DIR} = {}) {
  mkdirSync(outDir, {recursive: true});
  for (const app of Object.keys(APP_SEEDS)) {
    writeFileSync(join(outDir, `${app}.css`), seedCss(app));
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildSeeds();
}
